const QRCode = require('qrcode');
const crypto = require('crypto');
const Batch = require('../models/Batch');

class QRService {
  constructor() {
    this.secretKey = process.env.QR_SECRET_KEY || 'default-qr-secret-key';
  }

  /**
   * Generate a secure QR code for a batch
   */
  async generateQRForBatch(batchId) {
    try {
      const batch = await Batch.findOne({ batchId });
      if (!batch) {
        throw new Error('Batch not found');
      }

      // Create a secure payload with signature
      const payload = {
        batchId: batch.batchId,
        productName: batch.product.name,
        farmer: batch.farmer.farmerName,
        harvestDate: batch.harvest?.harvestDate,
        timestamp: Date.now(),
        version: '1.0'
      };

      // Generate signature to verify authenticity
      const signature = this.generateSignature(payload);
      const securePayload = {
        ...payload,
        signature,
        systemGenerated: true
      };

      // Generate QR code
      const qrCodeDataURL = await QRCode.toDataURL(JSON.stringify(securePayload), {
        width: 400,
        margin: 2,
        color: { dark: '#2c7744', light: '#FFFFFF' },
        errorCorrectionLevel: 'H'
      });

      // Update batch with QR code data
      batch.qrCode = JSON.stringify(securePayload);
      await batch.save();

      return {
        qrCodeDataURL,
        qrData: securePayload,
        traceUrl: `${process.env.FRONTEND_URL || 'http://localhost:3002'}/trace/${batch.batchId}`
      };
    } catch (error) {
      throw new Error(`QR generation failed: ${error.message}`);
    }
  }

  /**
   * Verify QR code authenticity
   */
  async verifyQR(qrData) {
    try {
      let parsedData;
      
      // Handle string or object input
      if (typeof qrData === 'string') {
        try {
          parsedData = JSON.parse(qrData);
        } catch (e) {
          return {
            isValid: false,
            isSystemGenerated: false,
            error: 'Invalid QR format'
          };
        }
      } else {
        parsedData = qrData;
      }

      // Check if it's system generated
      if (!parsedData.systemGenerated || !parsedData.signature) {
        return {
          isValid: false,
          isSystemGenerated: false,
          error: 'QR code not generated by our system'
        };
      }

      // Verify signature
      const { signature, ...dataWithoutSignature } = parsedData;
      const expectedSignature = this.generateSignature(dataWithoutSignature);
      
      if (signature !== expectedSignature) {
        return {
          isValid: false,
          isSystemGenerated: false,
          error: 'QR code signature verification failed'
        };
      }

      // Check if batch exists and get full data
      if (parsedData.batchId) {
        const batch = await Batch.findOne({ batchId: parsedData.batchId })
          .populate('farmer.farmerId', 'firstName lastName email phone')
          .populate('processor.processorId', 'companyName email phone');

        if (!batch) {
          return {
            isValid: false,
            isSystemGenerated: true,
            error: 'Batch not found in database'
          };
        }

        return {
          isValid: true,
          isSystemGenerated: true,
          qrData: parsedData,
          batchData: batch,
          verificationTime: new Date().toISOString()
        };
      }

      return {
        isValid: true,
        isSystemGenerated: true,
        qrData: parsedData
      };
    } catch (error) {
      return {
        isValid: false,
        isSystemGenerated: false,
        error: `Verification failed: ${error.message}`
      };
    }
  }

  /**
   * Generate signature for QR payload
   */
  generateSignature(payload) {
    const dataString = JSON.stringify(payload, Object.keys(payload).sort());
    return crypto
      .createHmac('sha256', this.secretKey)
      .update(dataString)
      .digest('hex');
  }

  /**
   * Get QR scan analytics
   */
  async getQRAnalytics(batchId) {
    try {
      const batch = await Batch.findOne({ batchId });
      if (!batch) {
        throw new Error('Batch not found');
      }

      return {
        batchId,
        qrGenerated: !!batch.qrCode,
        scanCount: batch.scanCount || 0,
        lastScanned: batch.lastScanned,
        generatedAt: batch.createdAt
      };
    } catch (error) {
      throw new Error(`Analytics failed: ${error.message}`);
    }
  }

  /**
   * Record QR scan
   */
  async recordScan(batchId, scanData = {}) {
    try {
      const batch = await Batch.findOne({ batchId });
      if (batch) {
        batch.scanCount = (batch.scanCount || 0) + 1;
        batch.lastScanned = new Date();
        
        // Store scan history if needed
        if (!batch.scanHistory) {
          batch.scanHistory = [];
        }
        
        batch.scanHistory.push({
          timestamp: new Date(),
          ...scanData
        });

        await batch.save();
      }
    } catch (error) {
      console.error('Error recording scan:', error);
    }
  }
}

module.exports = new QRService();